<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Logger\Module'               => __DIR__ . '/Module.php',
    'Logger\Event\LoggerEvent'    => __DIR__ . '/src/Logger/Event/LoggerEvent.php',
    'Logger\Listener\LogListener' => __DIR__ . '/src/Logger/Listener/LogListener.php',
);
