<!--  BE SURE TO RESET THIS TEMPLATE!!!! -->
<!--  TODO: set the action + display the form -->
<style>
.spacer {
    height: 50px;
    margin: 0 0 -50px 0;
    /* margin: 20px 0 -50px 0; use this if you want #container to have a 'bottom padding', in this case of 20px */
    background: transparent; /* you'll need this if #container's parent element has a different background from #container itself */
}
</style>
<h1>Post an Item</h1>
<?php $this->postForm->prepare() ?>
<?php $this->postForm->setAttribute('action', $this->url('market/post')) ?>
<?= $this->form()->openTag($this->postForm); ?>
<?php foreach ($this->postForm->getIterator() as $element) : ?>
<div>
    <div style="width: 200px;">
        <?php if ($element->getLabel()) : ?>
        <?= $this->formLabel($element) ?>
        <?php endif; ?>
    </div>
    <div style="width: 400px;">
        <?= $this->formElement($element) ?>
        <?php if ($this->formElementErrors($element)) : ?>
        <br>
        <?= $this->formElementErrors($element) ?>
        <?php endif; ?>
    </div>
</div>
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>
<?= Zend\Debug\Debug::dump($this->data, 'Data', FALSE); ?>
