<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Plugins\SomeDate'           => __DIR__ . '/src/Application/Plugins/SomeDate.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Module'                     => __DIR__ . '/Module.php',
);
