<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'layout/layout'                  => __DIR__ . '/view/layout/layout.phtml',
    'layout/alt-layout'              => __DIR__ . '/view/layout/alt-layout.phtml',
    'error/index'                    => __DIR__ . '/view/error/index.phtml',
    'error/404'                      => __DIR__ . '/view/error/404.phtml',
    'error/alt-error'                => __DIR__ . '/view/error/alt-error.phtml',
    'application/index/safe-landing' => __DIR__ . '/view/application/index/safe-landing.phtml',
    'application/index/index'        => __DIR__ . '/view/application/index/index.phtml',
    'application/index/whatever'     => __DIR__ . '/view/application/index/whatever.phtml',
);
