<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'market/post/invalid' => __DIR__ . '/view/market/post/invalid.phtml',
    'market/post/index'   => __DIR__ . '/view/market/post/index.phtml',
    'market/view/item'    => __DIR__ . '/view/market/view/item.phtml',
    'market/view/index'   => __DIR__ . '/view/market/view/index.phtml',
    'market/index/foo'    => __DIR__ . '/view/market/index/foo.phtml',
    'market/index/index'  => __DIR__ . '/view/market/index/index.phtml',
);
