<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'search/search/list'  => __DIR__ . '/view/search/search/list.phtml',
    'search/search/index' => __DIR__ . '/view/search/search/index.phtml',
    'search/test/index'   => __DIR__ . '/view/search/test/index.phtml',
);
